<?php

namespace Datacity\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	private function getCount($qb, $id)
	{
		return $qb->select($qb->expr()->count('s'))
				->where($qb->expr()->eq('u.id', $id))
				->getQuery()
				->getSingleScalarResult();
	}

	public function getSourcesNb($user)
	{
		$qb = $this->createQueryBuilder('u')->leftJoin('u.sources', 's');
		return $this->getCount($qb, $user->getId());
	}

	public function getDatasetOwnedNb($user)
	{
		$qb = $this->createQueryBuilder('u')->leftJoin('u.datasetOwned', 's');
		return $this->getCount($qb, $user->getId());
	}

	public function getDatasetContributedNb($user)
	{
		$qb = $this->createQueryBuilder('u')->leftJoin('u.datasetContributed', 's');
		return $this->getCount($qb, $user->getId());
	}

	public function getFollowingNb($user)
	{
		$qb = $this->createQueryBuilder('u')->leftJoin('u.following', 's');
		return $this->getCount($qb, $user->getId());
	}

	public function getFollowersNb($user)
	{
		$qb = $this->createQueryBuilder('u')->leftJoin('u.followers', 's');
		return $this->getCount($qb, $user->getId());
	}
}
