<?php

namespace Datacity\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function getCount()
	{
		$qb = $this->createQueryBuilder('c');
		return $qb->select($qb->expr()->count('c'))
				->getQuery()
				->getSingleScalarResult();
	}
}
